apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1 # Number of pods we want to create running some particular image
  selector: # Telling the deployment to monitor pods with a label of app: event-bus
    matchLabels:
      app: event-bus
  template: # Specify the exact config of a pod we want to create
    metadata:
      labels: # basically saying, we want to create a pod, with a label of app: event-bus.  Works together with the selector key above.
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: michaelj0/event-bus
---  # We can define our service in the same file as we define the deployment.  Common pattern.
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  selector:
    app: event-bus
  type: ClusterIP #Optional, Kubernetes defaults to ClusterIP
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005 #the port the node app is listening on
      targetPort: 4005