apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector:
    app: posts # This coorosponds to the template label we assigned in posts-depl, these selectors are kind of like HTML / CSS selectors (class, id, etc)
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000